# Generated by Django 3.1.1 on 2020-09-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_users', '0002_auto_20200908_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
    ]
