# Generated by Django 3.1.1 on 2020-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_users', '0003_auto_20200908_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
